---
# 開発ツールのインストール

# 便利なCLIツールのインストール
- name: 便利なCLIツールをインストール
  ansible.builtin.apt:
    name:
      - vim
      - git
      - htop
      - tmux
      - build-essential
      - net-tools
      - tree
      - jq
      - unzip
      - zip
      - ncdu
      - rsync
    state: present
  become: yes

# Docker のインストール
- name: Docker の古いバージョンを削除
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: yes

- name: Docker GPGキーを追加
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.asc
    mode: '0644'
  become: yes
  register: docker_gpg
  changed_when: false

- name: システムアーキテクチャを取得
  ansible.builtin.command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Ubuntu コードネームを取得
  ansible.builtin.command: lsb_release -cs
  register: ubuntu_codename
  changed_when: false

- name: Docker リポジトリファイルの存在と内容を確認
  ansible.builtin.shell: |
    test -f /etc/apt/sources.list.d/docker.list && \
    grep -q 'https://download.docker.com/linux/ubuntu' /etc/apt/sources.list.d/docker.list
  register: docker_repo_check
  changed_when: false
  failed_when: false

- name: Docker リポジトリを追加
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    filename: docker
    state: present
    update_cache: no
  become: yes
  when: docker_repo_check.rc != 0

- name: Docker パッケージをインストール
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: Docker サービスを起動・有効化
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: 現在のユーザーをdockerグループに追加
  ansible.builtin.user:
    name: "{{ default_user }}"
    groups: docker
    append: yes
  become: yes

- name: Docker Compose (standalone) の最新版をダウンロード
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: yes

- name: Docker のインストール確認
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false

- name: Docker Compose のインストール確認
  ansible.builtin.command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- name: Docker バージョン情報を表示
  ansible.builtin.debug:
    msg:
      - "{{ docker_version.stdout }}"
      - "{{ docker_compose_version.stdout }}"

# pyenv のインストール
- name: pyenv に必要なパッケージをインストール
  ansible.builtin.apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
    update_cache: yes
  become: yes

- name: pyenv がインストール済みかチェック
  ansible.builtin.stat:
    path: "/home/{{ default_user }}/.pyenv"
  register: pyenv_installed

- name: pyenv をインストール
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "/home/{{ default_user }}/.pyenv"
    version: master
  become: yes
  become_user: "{{ default_user }}"
  when: not pyenv_installed.stat.exists

- name: pyenv-virtualenv をインストール
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "/home/{{ default_user }}/.pyenv/plugins/pyenv-virtualenv"
    version: master
  become: yes
  become_user: "{{ default_user }}"
  when: not pyenv_installed.stat.exists

- name: .bashrc に pyenv 設定があるか確認
  ansible.builtin.shell: grep -q 'ANSIBLE MANAGED BLOCK - pyenv' "/home/{{ default_user }}/.bashrc"
  register: bashrc_pyenv_check
  changed_when: false
  failed_when: false
  become: yes
  become_user: "{{ default_user }}"

- name: .bashrc に pyenv 設定を追加
  ansible.builtin.blockinfile:
    path: "/home/{{ default_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    create: yes
  become: yes
  become_user: "{{ default_user }}"
  when: bashrc_pyenv_check.rc != 0

- name: .profile に pyenv 設定を追加
  ansible.builtin.blockinfile:
    path: "/home/{{ default_user }}/.profile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
    create: yes
  become: yes
  become_user: "{{ default_user }}"

- name: 開発ツールのインストール完了メッセージ
  ansible.builtin.debug:
    msg: "開発ツールのインストールが完了しました: CLI Tools, Docker, Docker Compose, pyenv"
