---
all:
  children:
    pc:
      hosts:
        ubuntu-pc:
          ansible_host: 192.168.10.109
          ansible_user: obitwo
          # ansible_become_password: "{{ vault_become_password }}"  # --ask-become-passを使用する場合はコメントアウト
