---
# Minikube のデフォルト設定
default_user: "obitwo"

# Minikubeのバージョン
minikube_version: "latest"

# Minikubeのドライバー
# 選択肢: docker, kvm2, virtualbox, none
minikube_driver: "docker"

# Minikubeクラスター設定
minikube_cpus: 2
minikube_memory: "4096mb"
minikube_disk_size: "20g"
minikube_nodes: 2

# CNI (Container Network Interface)
# 選択肢: calico, flannel, cilium, auto
minikube_cni: "calico"

# GPU設定
minikube_enable_gpu: true

# Kubernetes バージョン
kubernetes_version: "stable"

# アドオン
minikube_addons:
  - ingress
  - dashboard
  - metrics-server

# Minikubeの自動起動設定
minikube_autostart: false
